### ISSUE TITLE
Epic: Compatibility with v5 SDK

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#175]
- [x] Determine where the shim layer should live (within AEPCore or ACPCore)
- [x] Implement a shim layer to wrap old Core API calls into new Core API calls
- [x] Implement a shim layer to wrap old Lifecycle API calls into new Lifecycle API calls
- [x] Implement a shim layer to wrap old Identity API calls into new Identity API calls
- [x] Create open source repo with the compatibility layer
