### ISSUE TITLE
Epic: extensions final review

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#268]
- [ ] Compare the swift code with v5 code, to ensure the feature parity.
- [ ] Check the code coverage of unit test, add any missing tests.
- [ ] Compare the functional test with v5 module tests, add any tests if necessary.
- [ ] Compare the integration test with v5 compatibility tests, add any tests if necessary.
- [ ] Add manual tests
