### ISSUE TITLE
Epic: Documentation for Beta

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#316]
- [x] API Usage Documentation #323  
- [x] Services Usage Documentation #320 
- [x] Getting started with SDK #341 
- [x] Public AEP SDK docs 
- [ ] Turtorial?
- [ ] Video?
- [ ] Discoverable, well organized
- [ ] ?
