### ISSUE TITLE
Epic: Define Test strategy

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#33]
- [x] Unit test
- [x] Functional test (Fake network layer)
- [x] Performance test
- [x] Test harness? The current plan is Core will not share any testable.
- [x] Compatibility test (Hermetic test)? No
