### ISSUE TITLE
Epic : Distribution of Core SDK

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#34]
- [x] First step: Source code + Pods + Makefile 
- [x] Binaries? Static lib vs xcframework
- [x] How to distribute Rules Engine code with Core
-  SPM
-  Carthage
