### ISSUE TITLE
Epic:  Compatibility with Obj-C

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#35]
- [x] Make all public APIs Obj-C compatible:
   - [x] Core
   - [x] Configuration
   - [x] Lifecycle
   - [x] Identity
- [x] Allow Objective-C extensions to be developed
- [x] Decide if platform services should be compatible with Obj-C
- [x] Draft the guidelines on the best practices for handling compatibility issues
