### ISSUE TITLE
XDM Lifecycle Data

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#390]
- [x] Lifecycle Data sent as XDM events
- [x] Device and Environment info as XDM data
- [ ] Share data as XDM Shared State
- [x] End to end testing
- [x] Document the automatically collected data

**Comment by praveek** [comment]
@emdobrin We can create a separate issue for Phase 2 which includes  `Share data as XDM Shared State` based on our plans. 
`
