### ISSUE TITLE
XDM Identity Data

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#391]
- [x] Send Identity Data sent as XDM events 
- [ ] Support for AID (namespace AAID), VID (request standard namespace)
- [ ] Support for IDFA (namespace IDFA)
- [ ] Convert EdgeHost to location hint
- [x] Share data as XDM Shared State to be attached on each event
- [ ] Getter for IdentityMap for hybrid app
- [x] End to end testing
- [ ] Document the supported workflows

**Comment by emdobrin** [comment]
XDM Shared state support has been added to both iOS and Android core and the new xdm data will be in use starting with Edge v1.1.0.
Closing this task as the scope for Core has been achieved and the remaining items should be handled as part of the Edge Identity extension:
https://github.com/adobe/aepsdk-edgeidentity-ios
https://github.com/adobe/aepsdk-edgeidentity-android
