### ISSUE TITLE
Epic: Implement Signal Extension

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#43]
- [x] #161 Add Signal target to AEPCore.xcodeproj
- [x] #162 Stub Signal extension 
- [x] #163 Handle Configuration Response Content Events
- [x] #164 Handle Rules Engine Response Content Events
- [x] #165 Implement SignalHitProcessor
- [x] #166 Implement a DataQueue & HitQueue
- [x] #167 Implement processing of PII consequences
- [x] #168 Implement processing of postback consequences
- [x] #169 Implement processing of open url consequences
- [x] #170 Signals Functional Tests
