### ISSUE TITLE
Epic: Implement Identity Extension

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#45]
- [x] Implement Identity public APIs and stub Identity extension
- [x] Add functions/helpers to send opt-out hit
- [x] Implement a struct to maintain Identity properties
- [x] Implement MID generation
- [x] Implement logic for sync identifiers
- [x] Implement identity hit processing
- [x] Add a PushID Manager
- [x] Handle Identity Request Identity events
- [x] Handle Configuration Response Content Events
- [ ] Handle Audience response content events (deferred)
- [ ] Handle Analytics response identity events (deferred)
- [x] Identity Functional Tests
