### ISSUE TITLE
Epic: CI/CD

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#47]
- [x] Use CircleCI before the repo is public
- [x] Makefile
- [x] CI/CD tools.
- [ ] Split CircleCI jobs (build-and-test, codecov) and add branch protection rules on main branch for both jobs, on dev branch for build-and-test only
- [x] Release automation
-  Git hub actions.
