### ISSUE TITLE
Epic: Sample App

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#48]
- [x] Objc-C sample app
- [x] Swift sample app
- [x] Objc-C sample extension
- [x] Swift sample extension
