### ISSUE TITLE
Epic: Event hub

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#53]
- [x] Register listeners
- [x] Register extensions and creating extensions
- [x] Updating and getting shared state
- [x] Dispatching an event 
- [x] Timeout control on response listeners
- [x] Error callbacks on response listeners
- [x] Shared state of Extension details
- [x] Owner of operation orderer
