### ISSUE TITLE
Epic: Integration with Rules Engine

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#54]
- [x] Integrate Eventhub with Rules Engine (estimate: 1 weeks) #95 
- [x] Consequence handling
    - [x] Event  (estimate: 1/2 week) #97 
    - [x] Data modification (attach, modify, delete)  (estimate: 2 weeks) #85 
- [x] Json Rule parser (estimate: 1 week) #96 
- [x] Launch Rule download (estimate: 1 week) #94 
- [x] Token replacement (estimate: 1 week) #92 
- [x] First launch support (estimate: 1 week) #98
